version: '3.8'

services:
  proxy:
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - chat
      - ai
      - users-api

  chat:
    build:
      context: ./chat
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./chat:/usr/local/src/chat
      - /usr/local/src/chat/node_modules
    ports:
      - 8003:8003
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - PORT=8003
    depends_on:
      - redis
      - mongo
      - users

  ai:
    build:
      context: ./ai
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./ai:/usr/local/src/ai
    ports:
      - 8002:5000 
    entrypoint: sh -c "python3 /usr/local/src/ai/server.py"

  users:
    build:
      context: ./users
      dockerfile: ./docker/Dockerfile
    entrypoint: sh -c "wait-for-it -t 300 mysql:3306 && chown -R www-data:www-data /usr/local/src/users && /usr/bin/composer install && php /usr/local/src/users/artisan migrate --force && php-fpm"
    volumes:
      - ./users:/usr/local/src/users
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=users
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
    depends_on:
      - mysql
  users-api:
    image: nginx:1.19-alpine
    volumes:
      - ./users:/usr/local/src/users
      - ./users/docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8001:80
    depends_on:
      - users

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33060:3306"
    volumes:
      - mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    ports:
      - 63790:6379
    
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mysql:
  redis:
  mongo: